# p3 configuration file

setup:
  rootdir: /data3/erichards/codes/p3/test/    # images root directory
  year: 2017
  month: 08
  day: ['30']                               # list of days to process; [] = all
  dbdir: /data3/erichards/codes/p3/test/      # database directory
  dbname: test.sqlite                         # database name
  overwrite: no                               # overwrite database if exists?
  catalogs: ['TGSS', 'NVSS', 'FIRST', 'SUMSS', 'WENSS'] # list of sky catalogs
  reprocess: no    # If False (or no), already processed image will be skipped

pybdsf_params:
  mode: default                               # or minimize_islands
  # Specify all PyBDSF parameters here
  thresh: hard
  #trim_box: !!python/tuple [400, 1300, 400, 1300]       # need to force tuple
  #rms_box: !!python/tuple [30, 10]

catalog_matching:
  do_for: new                                 # or all
