# p3 configuration file

stages:
                              # processing steps; yes | no  or  True | False
  source finding: yes         # if yes, provide pybdsf_params
  source association: yes     # if yes, provide database name/path below
  catalog matching: yes       # cross-match with sky survey catalogs?

options:
                              # processing options; yes | no or True | False
  save to database: yes       # save results to database?
  quality checks: no          # run image & source count quality checks?
  overwrite: no               # overwrite database if exists?
  reprocess: yes              # redo selected stages even if done previously?
  redo match: no              # redo catalog matching for all sources?

setup:
  rootdir: /path/to/data/
  year: 2017
  month: 08
  day: [30]                   # list of days to process; [] = all
  dbname: vlite
  dbuser: postgres
  catalogs: [FIRST, GLEAM, NVSS, SUMSS, TGSS, WENSS]   # list of sky catalogs

pybdsf_params:
  mode: default               # default | minimize_islands
  # Specify all PyBDSF parameters here
  thresh: hard
  #trim_box: !!python/tuple [400, 1300, 400, 1300]  # need to force tuple
  #rms_box: !!python/tuple [30, 10]

matching:
  resolution tolerance: 5.0   # (in arcsec) allowed difference in beam sizes
        # for images to be considered as having similar spatial resolutions