# p3 configuration file

stages: # optional processing steps; yes | no  or  True | False
  save_to_database: yes       # add image(s) and sources to database?
        # if yes, provide database name/path
  quality_checks: no          # run image quality checks?
  source_finding: yes         # if yes, provide pybdsf_params
  source_association: yes     # if yes, provide database name/path
  catalog_matching: no        # cross-match with sky survey catalogs?
        # if yes, provide sky catalog database name and list of catalogs to use

setup:
  rootdir: /data3/erichards/codes/p3/test/
  year: 2017
  month: 08
  day: ['30']                 # list of days to process; [] = all
  dbname: /data3/erichards/codes/p3/test/test.sqlite
  overwrite: no               # overwrite database if exists?
  reprocess: yes              # redo source finding on image if done before?
  catdb: SkyCatalogs.sqlite   # sky catalog database name
  catalogs: ['TGSS', 'NVSS', 'FIRST', 'SUMSS', 'WENSS']  # list of sky catalogs

pybdsf_params:
  mode: default               # default | minimize_islands
  # Specify all PyBDSF parameters here
  thresh: hard
  #trim_box: !!python/tuple [400, 1300, 400, 1300]  # need to force tuple
  #rms_box: !!python/tuple [30, 10]

matching:
  res_tol: 1.0                # (in arcsec) allowed difference in beam sizes
         # for images to be considered as having similar spatial resolutions
  catalog_match: new          # new | all sources in AssocSource table
